# Generated by Django 4.0.3 on 2022-08-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Becado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('area_de_interes', models.CharField(choices=[('Tecnología', 'Tecnología'), ('Salud', 'Salud'), ('Artes y Humanidades', 'Artes Y Humanidades'), ('Ciencias Sociales', 'Ciencias Sociales'), ('Ingenería', 'Ingenería')], default='Tecnología', max_length=20)),
                ('grado_academico', models.CharField(choices=[('Licenciatura', 'Licenciatura'), ('Maestria', 'Maestria'), ('Doctorado', 'Doctorado'), ('Curso', 'Curso')], default='Curso', max_length=15)),
            ],
        ),
    ]
