# Generated by Django 4.0.3 on 2022-08-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='becado',
            name='Estatus',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Egresado', 'Egresado')], default='Activo', max_length=15),
        ),
    ]
