# Generated by Django 4.0.3 on 2022-08-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becados', '0002_becado_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='becado',
            old_name='apellido_materno',
            new_name='APELLIDO_MATERNO',
        ),
        migrations.RenameField(
            model_name='becado',
            old_name='apellido_paterno',
            new_name='APELLIDO_PATERNO',
        ),
        migrations.RenameField(
            model_name='becado',
            old_name='correo_electronico',
            new_name='CORREO_ELECTRONICO',
        ),
        migrations.RenameField(
            model_name='becado',
            old_name='nombre',
            new_name='NOMBRE',
        ),
        migrations.AlterField(
            model_name='becado',
            name='area_de_interes',
            field=models.CharField(choices=[('Tecnología', 'Tecnología'), ('Salud', 'Salud'), ('Artes y Humanidades', 'Artes y Humanidades'), ('Ciencias_Sociales', 'Ciencias Sociales'), ('Ingenería', 'Ingenería')], default='Tecnología', max_length=20),
        ),
    ]
