# Generated by Django 4.0.6 on 2022-08-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=56)),
                ('pais', models.CharField(max_length=32)),
                ('area', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('web_page', models.URLField(max_length=256)),
            ],
            options={
                'db_table': 'orgs',
            },
        ),
    ]
