# Generated by Django 4.0.6 on 2022-08-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_rol_organizacion_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='rol',
            field=models.CharField(choices=[('Organizacion', 'Organizacion'), ('Becado', 'Becado')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
