# Generated by Django 4.0.6 on 2022-08-07 16:11

from django.db import migrations, models
import organizacion.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0003_alter_organizacion_rol_delete_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacion',
            name='rol',
        ),
        migrations.AddField(
            model_name='organizacion',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to=organizacion.models.upload_img),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='tipo',
            field=models.BooleanField(default=True, verbose_name='Organización'),
        ),
    ]
