# Generated by Django 4.0.6 on 2022-08-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0004_remove_organizacion_rol_organizacion_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='tipo',
            field=models.BooleanField(default=False, verbose_name='Organización'),
        ),
    ]
