# Generated by Django 4.0.6 on 2022-08-07 17:18

from django.db import migrations, models
import organizacion.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0005_alter_organizacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='image',
            field=models.ImageField(default='imgs_org/default.png', null=True, upload_to=organizacion.models.upload_img),
        ),
    ]
