# Generated by Django 4.0.6 on 2022-08-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0006_alter_organizacion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='area',
            field=models.CharField(choices=[('Tecnología', 'Tecnología'), ('Salud', 'Salud'), ('Artes y Humanidades', 'Artes y Humanidades'), ('Ciencias Sociales', 'Ciencias Sociales'), ('Ingeniería', 'Ingeniería')], default='Tecnología', max_length=256),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='tipo',
            field=models.BooleanField(default=True, verbose_name='Organización'),
        ),
    ]
