# Generated by Django 4.1 on 2022-08-07 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AreaInteres', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('linkedIn', models.CharField(max_length=50)),
                ('beca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comunidad.beca')),
            ],
            options={
                'db_table': 'Comunidad',
            },
        ),
    ]
