# Generated by Django 4.1 on 2022-08-07 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='beca',
        ),
    ]
